[program:printer]
process_name=printer_%(process_num)02d
command=node printer_node.js
directory=/home/mustang-a/Documents/printer_servers
autostart=true
autorestart=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/home/mustang-a/Documents/printer_servers/logs/worker-printer.log

